services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: data_cleaning_backend
    ports:
      - "8000:8000"
    volumes:
      - ./working:/working
      - ./backend:/app/backend
      - ./dataset:/app/dataset
      - ./config:/app/config
    environment:
      - MODEL_PATH=/working
      - DATABASE_URL=postgresql://user:password@db:5432/cleandata
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
      - HF_REPO_ID=duyhung753951/clean-data_vinai_phobert-base-v2
    depends_on:
      - db
    # Cài đặt nóng các thư viện missing, tải model và khởi động server
    command: >
      sh -c "pip install --no-cache-dir scikit-learn psycopg2-binary pyahocorasick pyvi requests python-dotenv python-multipart openpyxl && 
             python backend/scripts/download_model.py && 
             uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:15-alpine
    container_name: data_cleaning_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cleandata
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: data_cleaning_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  pgdata:
