version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: data_cleaning_backend
    ports:
      - "8000:8000"
    volumes:
      - ./working:/working
    environment:
      - MODEL_PATH=/working

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: data_cleaning_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
